version: '3.7'

services:

  # Web Server Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - db

  # Database Service
  db:
    image: mariadb:11.1
    container_name: db
    restart: on-failure
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - "3400:80"
    depends_on:
      - db

  # PHP Service
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
